org: keichi
app: gomi
service: gomi

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: prod
  region: ap-northeast-1

functions:
  getCalendar:
    handler: handler.getCalendar
    events:
      - httpApi:
          path: /calendar
          method: GET
